#lang racket/base

(require
 "async.rkt"
 "sync.rkt"
 "../util/time.rkt")

; autogenerated
(require (prefix-in 2_4-  "../../prim_fifo_sync_2_4.rkt"))
(require (prefix-in 33_2- "../../prim_fifo_sync_33_2.rkt"))
(require (prefix-in 5_4-  "../../prim_fifo_async_5_4.rkt"))
(require (prefix-in 8_8-  "../../prim_fifo_async_8_8.rkt"))
(require (prefix-in 17_4- "../../prim_fifo_async_17_4.rkt"))
(require (prefix-in 100_3- "../../prim_fifo_async_100_3.rkt"))

(provide verify-fifos)

(define (verify-fifos)
  ; spi_device.u_fwmode_arb.u_req_fifo.gen_normal_fifo.storage
  (let ()
    (define-values (_ t)
      (time
       (verify-prim-fifo-sync
        2_4-new-symbolic-prim_fifo_sync_s
        2_4-prim_fifo_sync_t
        2_4-registers
        2_4-outputs
        2 4)))
    (printf "2x4 FIFO verified in ~as~n" (fmt-time t)))

  ; tl_adapter_ram_main.u_rspfifo.gen_normal_fifo.storage
  (let ()
    (define-values (_ t)
      (time
       (verify-prim-fifo-sync
        33_2-new-symbolic-prim_fifo_sync_s
        33_2-prim_fifo_sync_t
        33_2-registers
        33_2-outputs
        33 2)))
    (printf "33x2 FIFO verified in ~as~n" (fmt-time t)))

  ; usbdev.usbdev_avfifo
  (let ()
    (define-values (_ t)
      (time
       (verify-prim-fifo-async
        5_4-new-symbolic-prim_fifo_async_s
        5_4-prim_fifo_async_t
        5_4-fix-mem
        5_4-registers
        5_4-outputs
        5 4)))
    (printf "5x4 FIFO verified in ~as~n" (fmt-time t)))

  ; usbdev.usbdev_rxfifo
  (let ()
    (define-values (_ t)
      (time
       (verify-prim-fifo-async
        17_4-new-symbolic-prim_fifo_async_s
        17_4-prim_fifo_async_t
        17_4-fix-mem
        17_4-registers
        17_4-outputs
        17 4)))
    (printf "17x4 FIFO verified in ~as~n" (fmt-time t)))

  ; spi_device.u_rx_fifo
  ; spi_device.u_tx_fifo
  (let ()
    (define-values (_ t)
      (time
       (verify-prim-fifo-async
        8_8-new-symbolic-prim_fifo_async_s
        8_8-prim_fifo_async_t
        8_8-fix-mem
        8_8-registers
        8_8-outputs
        8 8)))
    (printf "8x8 FIFO verified in ~as~n" (fmt-time t)))

  ; u_xbar_main.u_asf_21.reqfifo.storage_rest
  (let ()
    (define-values (_ t)
      (time
       (verify-prim-fifo-async
        100_3-new-symbolic-prim_fifo_async_s
        100_3-prim_fifo_async_t
        100_3-fix-mem
        100_3-registers
        100_3-outputs
        100 3)))
    (printf "100x3 FIFO verified in ~as~n" (fmt-time t)))
)

(module+ main
  (define-values (_ t) (time (verify-fifos)))
  (printf "All FIFOs verified in ~as ~n" (fmt-time t)))
