#lang racket/base
(provide main-registers)
(define main-registers
  '(
    |core.u_core.if_stage_i.prefetch_buffer_i.fetch_addr_q|
    |core.u_core.cs_registers_i.gen_trigger_regs.tmatch_value_q|
    |core.u_core.cs_registers_i.gen_trigger_regs.tmatch_control_q|
    |core.u_core.cs_registers_i.mcountinhibit_q|
    |core.u_core.cs_registers_i.priv_lvl_q|
    |core.u_core.cs_registers_i.mstatus_q|
    |core.u_core.cs_registers_i.mie_q|
    |core.u_core.cs_registers_i.mscratch_q|
    |core.u_core.cs_registers_i.mepc_q|
    |core.u_core.cs_registers_i.mcause_q|
    |core.u_core.cs_registers_i.mtval_q|
    |core.u_core.cs_registers_i.mtvec_q|
    |core.u_core.cs_registers_i.dcsr_q|
    |core.u_core.cs_registers_i.depc_q|
    |core.u_core.cs_registers_i.dscratch0_q|
    |core.u_core.cs_registers_i.dscratch1_q|
    |core.u_core.cs_registers_i.mstack_q|
    |core.u_core.cs_registers_i.mstack_epc_q|
    |core.u_core.cs_registers_i.mstack_cause_q|
    |core.u_core.cs_registers_i.mcycle_counter_i.g_counter[0].g_counter_exists.counter_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.gen_multdiv_fast.mult_state_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.intermediate_val_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.op_denominator_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.op_numerator_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.op_quotient_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.div_counter_q|
    |core.u_core.ex_block_i.gen_multdiv_fast.multdiv_i.md_state_q|
    |core.u_core.id_stage_i.g_branch_set_flopped.branch_set_q|
    |core.u_core.id_stage_i.controller_i.nmi_mode_q|
    |core.u_core.id_stage_i.controller_i.debug_mode_q|
    |core.u_core.id_stage_i.controller_i.exc_req_q|
    |core.u_core.id_stage_i.controller_i.illegal_insn_q|
    |core.u_core.if_stage_i.offset_in_init_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.discard_req_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.stored_addr_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.rdata_q [95:64]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.err_q [2]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.rdata_q [63:32]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.err_q [1]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.rdata_q [31:0]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.err_q [0]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.instr_addr_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[7].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[6].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[5].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[4].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[3].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[2].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[1].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.mcounters_variable_i.g_counter[0].g_counter_exists.counter_q|
    |core.u_core.cs_registers_i.minstret_counter_i.g_counter[0].g_counter_exists.counter_q|
    |core.u_core.id_stage_i.instr_multicycle_done_q|
    |core.u_core.id_stage_i.id_wb_fsm_cs|
    |core.u_core.id_stage_i.controller_i.ctrl_fsm_cs|
    |core.u_core.id_stage_i.controller_i.load_err_q|
    |core.u_core.id_stage_i.controller_i.store_err_q|
    |core.u_core.id_stage_i.registers_i.rf_reg_tmp|
    |core.u_core.if_stage_i.instr_valid_id_o|
    |core.u_core.if_stage_i.instr_new_id_o|
    |core.u_core.if_stage_i.instr_rdata_id_o|
    |core.u_core.if_stage_i.instr_rdata_alu_id_o|
    |core.u_core.if_stage_i.instr_rdata_c_id_o|
    |core.u_core.if_stage_i.instr_is_compressed_id_o|
    |core.u_core.if_stage_i.instr_fetch_err_o|
    |core.u_core.if_stage_i.illegal_c_insn_id_o|
    |core.u_core.if_stage_i.pc_id_o|
    |core.u_core.if_stage_i.prefetch_buffer_i.valid_req_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.rdata_outstanding_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.branch_discard_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.rdata_pmp_err_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.valid_q|
    |core.u_core.load_store_unit_i.handle_misaligned_q|
    |core.u_core.load_store_unit_i.pmp_err_q|
    |core.u_core.load_store_unit_i.lsu_err_q|
    |core.u_core.load_store_unit_i.ls_fsm_cs|
    |core.u_core.load_store_unit_i.addr_last_q|
    |core.u_core.load_store_unit_i.rdata_offset_q|
    |core.u_core.load_store_unit_i.data_type_q|
    |core.u_core.load_store_unit_i.data_sign_ext_q|
    |core.u_core.load_store_unit_i.data_we_q|
    |core.u_core.load_store_unit_i.rdata_q|
    |spi_device.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.b_rdata_o|
    |spi_device.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.a_rdata_o|
    |spi_device.u_tlul2sram.u_reqfifo.gen_normal_fifo.storage[0]|
    |spi_device.u_tlul2sram.u_rspfifo.gen_normal_fifo.storage[0]|
    |usbdev.u_tlul2sram.u_reqfifo.gen_normal_fifo.storage[0]|
    |usbdev.u_tlul2sram.u_rspfifo.gen_normal_fifo.storage[0]|
    |spi_device.rxlvl|
    |spi_device.txlvl|
    |spi_device.sram_rxf_full_q|
    |spi_device.u_fwmode_arb.gen_arb_ppc.u_reqarb.gen_normal_case.mask|
    |spi_device.u_fwmode_arb.u_req_fifo.gen_normal_fifo.fifo_rptr|
    |spi_device.u_fwmode_arb.u_req_fifo.gen_normal_fifo.fifo_wptr|
    |spi_device.u_memory_2p.a_rvalid_sram|
    |spi_device.u_memory_2p.b_rvalid_sram|
    |spi_device.u_reg.u_cfg_cpha.q|
    |spi_device.u_reg.u_cfg_cpol.q|
    |spi_device.u_reg.u_cfg_rx_order.q|
    |spi_device.u_reg.u_cfg_timer_v.q|
    |spi_device.u_reg.u_cfg_tx_order.q|
    |spi_device.u_reg.u_control_abort.q|
    |spi_device.u_reg.u_control_mode.q|
    |spi_device.u_reg.u_control_rst_rxfifo.q|
    |spi_device.u_reg.u_control_rst_txfifo.q|
    |spi_device.u_reg.u_fifo_level_rxlvl.q|
    |spi_device.u_reg.u_fifo_level_txlvl.q|
    |spi_device.u_reg.u_intr_enable_rxerr.q|
    |spi_device.u_reg.u_intr_enable_rxf.q|
    |spi_device.u_reg.u_intr_enable_rxlvl.q|
    |spi_device.u_reg.u_intr_enable_rxoverflow.q|
    |spi_device.u_reg.u_intr_enable_txlvl.q|
    |spi_device.u_reg.u_intr_enable_txunderflow.q|
    |spi_device.u_reg.u_intr_state_rxerr.q|
    |spi_device.u_reg.u_intr_state_rxf.q|
    |spi_device.u_reg.u_intr_state_rxlvl.q|
    |spi_device.u_reg.u_intr_state_rxoverflow.q|
    |spi_device.u_reg.u_intr_state_txlvl.q|
    |spi_device.u_reg.u_intr_state_txunderflow.q|
    |spi_device.u_reg.u_reg_if.rdata|
    |spi_device.u_reg.u_reg_if.error|
    |spi_device.u_reg.u_reg_if.reqid|
    |spi_device.u_reg.u_reg_if.reqsz|
    |spi_device.u_reg.u_reg_if.rspop|
    |spi_device.u_reg.u_reg_if.outstanding|
    |spi_device.u_reg.u_rxf_addr_base.q|
    |spi_device.u_reg.u_rxf_addr_limit.q|
    |spi_device.u_reg.u_rxf_ptr_rptr.q|
    |spi_device.u_reg.u_rxf_ptr_wptr.q [11:0]|
    |spi_device.u_reg.u_socket.num_req_outstanding|
    |spi_device.u_reg.u_socket.dev_select_outstanding|
    |spi_device.u_reg.u_socket.err_resp.err_rsp_pending|
    |spi_device.u_reg.u_socket.err_resp.err_opcode|
    |spi_device.u_reg.u_socket.err_resp.err_source|
    |spi_device.u_reg.u_socket.err_resp.err_size|
    |spi_device.u_reg.u_socket.err_resp.err_req_pending|
    |spi_device.u_reg.u_txf_addr_base.q|
    |spi_device.u_reg.u_txf_addr_limit.q|
    |spi_device.u_reg.u_txf_ptr_rptr.q [11:0]|
    |spi_device.u_reg.u_txf_ptr_wptr.q|
    |spi_device.u_rx_fifo.fifo_rptr_gray|
    |spi_device.u_rx_fifo.fifo_rptr|
    |spi_device.u_rx_fifo.sync_wptr.q|
    |spi_device.u_rxf_ctrl.sram_req|
    |spi_device.u_rxf_ctrl.sram_write|
    |spi_device.u_rxf_ctrl.byte_enable|
    |spi_device.u_rxf_ctrl.pos|
    |spi_device.u_rxf_ctrl.cur_timer|
    |spi_device.u_rxf_ctrl.wptr|
    |spi_device.u_rxf_ctrl.st|
    |spi_device.u_rxf_overflow.dst_level_q|
    |spi_device.u_rxf_overflow.prim_flop_2sync.q|
    |spi_device.u_sync_csb.q|
    |spi_device.u_sync_rxf.q|
    |spi_device.u_sync_txe.q|
    |spi_device.u_tlul2sram.u_reqfifo.gen_normal_fifo.fifo_rptr|
    |spi_device.u_tlul2sram.u_reqfifo.gen_normal_fifo.fifo_wptr|
    |spi_device.u_tlul2sram.u_rspfifo.gen_normal_fifo.fifo_rptr|
    |spi_device.u_tlul2sram.u_rspfifo.gen_normal_fifo.fifo_wptr|
    |spi_device.u_tx_fifo.storage_first|
    |spi_device.u_tx_fifo.fifo_rptr_sync|
    |spi_device.u_tx_fifo.fifo_wptr_gray|
    |spi_device.u_tx_fifo.fifo_wptr|
    |spi_device.u_tx_fifo.sync_rptr.q|
    |spi_device.u_txf_ctrl.sram_rdata_q|
    |spi_device.u_txf_ctrl.sram_req|
    |spi_device.u_txf_ctrl.rptr|
    |spi_device.u_txf_ctrl.wptr_q|
    |spi_device.u_txf_ctrl.pos|
    |spi_device.u_txf_ctrl.st|
    |spi_device.u_txf_underflow.dst_level_q|
    |spi_device.u_txf_underflow.prim_flop_2sync.q|
    |tl_adapter_ram_main.u_reqfifo.gen_normal_fifo.fifo_rptr|
    |tl_adapter_ram_main.u_rspfifo.gen_normal_fifo.fifo_rptr|
    |tl_adapter_ram_main.u_rspfifo.gen_normal_fifo.fifo_wptr|
    |tl_adapter_rom.u_reqfifo.gen_normal_fifo.fifo_rptr|
    |tl_adapter_rom.u_rspfifo.gen_normal_fifo.fifo_rptr|
    |tl_adapter_rom.u_rspfifo.gen_normal_fifo.fifo_wptr|
    |u_xbar_main.u_asf_21.reqfifo.fifo_rptr_sync|
    |u_xbar_main.u_asf_21.reqfifo.fifo_rptr_gray|
    |u_xbar_main.u_asf_21.reqfifo.fifo_rptr|
    |u_xbar_main.u_asf_21.reqfifo.sync_rptr.q|
    |u_xbar_main.u_asf_21.reqfifo.sync_rptr.intq|
    |u_xbar_main.u_asf_21.reqfifo.sync_wptr.q|
    |u_xbar_main.u_asf_21.reqfifo.sync_wptr.intq|
    |u_xbar_main.u_asf_21.rspfifo.storage_first|
    |u_xbar_main.u_asf_21.rspfifo.fifo_rptr_sync|
    |u_xbar_main.u_asf_21.rspfifo.fifo_rptr_gray|
    |u_xbar_main.u_asf_21.rspfifo.fifo_rptr|
    |u_xbar_main.u_asf_21.rspfifo.fifo_wptr_gray|
    |u_xbar_main.u_asf_21.rspfifo.fifo_wptr|
    |u_xbar_main.u_asf_21.rspfifo.sync_rptr.q|
    |u_xbar_main.u_asf_21.rspfifo.sync_rptr.intq|
    |u_xbar_main.u_asf_21.rspfifo.sync_wptr.q|
    |u_xbar_main.u_asf_21.rspfifo.sync_wptr.intq|
    |u_xbar_peri.u_s1n_6.num_req_outstanding|
    |u_xbar_peri.u_s1n_6.dev_select_outstanding|
    |u_xbar_peri.u_s1n_6.err_resp.err_rsp_pending|
    |u_xbar_peri.u_s1n_6.err_resp.err_opcode|
    |u_xbar_peri.u_s1n_6.err_resp.err_source|
    |u_xbar_peri.u_s1n_6.err_resp.err_size|
    |u_xbar_peri.u_s1n_6.err_resp.err_req_pending|
    |uart.u_reg.u_ctrl_llpbk.q|
    |uart.u_reg.u_ctrl_nco.q|
    |uart.u_reg.u_ctrl_nf.q|
    |uart.u_reg.u_ctrl_parity_en.q|
    |uart.u_reg.u_ctrl_parity_odd.q|
    |uart.u_reg.u_ctrl_rx.q|
    |uart.u_reg.u_ctrl_rxblvl.q|
    |uart.u_reg.u_ctrl_slpbk.q|
    |uart.u_reg.u_ctrl_tx.q|
    |uart.u_reg.u_fifo_ctrl_rxilvl.q|
    |uart.u_reg.u_fifo_ctrl_rxrst.q|
    |uart.u_reg.u_fifo_ctrl_rxrst.qe|
    |uart.u_reg.u_fifo_ctrl_txilvl.q|
    |uart.u_reg.u_fifo_ctrl_txrst.q|
    |uart.u_reg.u_intr_enable_rx_break_err.q|
    |uart.u_reg.u_intr_enable_rx_frame_err.q|
    |uart.u_reg.u_intr_enable_rx_overflow.q|
    |uart.u_reg.u_intr_enable_rx_parity_err.q|
    |uart.u_reg.u_intr_enable_rx_timeout.q|
    |uart.u_reg.u_intr_enable_rx_watermark.q|
    |uart.u_reg.u_intr_enable_tx_empty.q|
    |uart.u_reg.u_intr_enable_tx_watermark.q|
    |uart.u_reg.u_intr_state_rx_break_err.q|
    |uart.u_reg.u_intr_state_rx_frame_err.q|
    |uart.u_reg.u_intr_state_rx_overflow.q|
    |uart.u_reg.u_intr_state_rx_parity_err.q|
    |uart.u_reg.u_intr_state_rx_timeout.q|
    |uart.u_reg.u_intr_state_rx_watermark.q|
    |uart.u_reg.u_intr_state_tx_empty.q|
    |uart.u_reg.u_intr_state_tx_watermark.q|
    |uart.u_reg.u_ovrd_txen.q|
    |uart.u_reg.u_ovrd_txval.q|
    |uart.u_reg.u_reg_if.rdata|
    |uart.u_reg.u_reg_if.error|
    |uart.u_reg.u_reg_if.reqid|
    |uart.u_reg.u_reg_if.reqsz|
    |uart.u_reg.u_reg_if.rspop|
    |uart.u_reg.u_reg_if.outstanding|
    |uart.u_reg.u_timeout_ctrl_en.q|
    |uart.u_reg.u_timeout_ctrl_val.q|
    |uart.u_reg.u_wdata.q|
    |uart.u_reg.u_wdata.qe|
    |uart.uart_core.rx_fifo_depth_prev_q|
    |uart.uart_core.rx_timeout_count_q|
    |uart.uart_core.tx_watermark_prev_q|
    |uart.uart_core.rx_watermark_prev_q|
    |uart.uart_core.tx_uart_idle_q|
    |uart.uart_core.rx_val_q|
    |uart.uart_core.rx_sync_q1|
    |uart.uart_core.rx_sync_q2|
    |uart.uart_core.tx_out_q|
    |uart.uart_core.nco_sum_q|
    |uart.uart_core.break_st_q|
    |uart.uart_core.allzero_cnt_q|
    |uart.uart_core.sync_rx.q|
    |uart.uart_core.u_uart_rxfifo.gen_normal_fifo.fifo_rptr|
    |uart.uart_core.u_uart_rxfifo.gen_normal_fifo.fifo_wptr|
    |uart.uart_core.u_uart_txfifo.gen_normal_fifo.fifo_rptr|
    |uart.uart_core.u_uart_txfifo.gen_normal_fifo.fifo_wptr|
    |uart.uart_core.uart_rx.rx_valid_q|
    |uart.uart_core.uart_rx.sreg_q|
    |uart.uart_core.uart_rx.bit_cnt_q|
    |uart.uart_core.uart_rx.baud_div_q|
    |uart.uart_core.uart_rx.tick_baud_q|
    |uart.uart_core.uart_rx.idle_q|
    |uart.uart_core.uart_tx.sreg_q|
    |uart.uart_core.uart_tx.bit_cnt_q|
    |uart.uart_core.uart_tx.tx_q|
    |uart.uart_core.uart_tx.baud_div_q|
    |uart.uart_core.uart_tx.tick_baud_q|
    |usbdev.cdc_usb_to_sys.q|
    |usbdev.i_usbdev_iomux.cdc_io_to_sys.q|
    |usbdev.sync_usb_event_av_empty.dst_level_q|
    |usbdev.sync_usb_event_av_empty.prim_flop_2sync.q|
    |usbdev.sync_usb_event_frame.dst_level_q|
    |usbdev.sync_usb_event_frame.prim_flop_2sync.q|
    |usbdev.sync_usb_event_rx_bitstuff_err.dst_level_q|
    |usbdev.sync_usb_event_rx_bitstuff_err.prim_flop_2sync.q|
    |usbdev.sync_usb_event_rx_crc_err.dst_level_q|
    |usbdev.sync_usb_event_rx_crc_err.prim_flop_2sync.q|
    |usbdev.sync_usb_event_rx_full.dst_level_q|
    |usbdev.sync_usb_event_rx_full.prim_flop_2sync.q|
    |usbdev.sync_usb_event_rx_pid_err.dst_level_q|
    |usbdev.sync_usb_event_rx_pid_err.prim_flop_2sync.q|
    |usbdev.syncevent.d_sync_q|
    |usbdev.syncevent.prim_flop_2sync.q|
    |usbdev.u_memory_2p.a_rvalid_sram|
    |usbdev.u_reg.u_avbuffer.q|
    |usbdev.u_reg.u_avbuffer.qe|
    |usbdev.u_reg.u_configin0_buffer0.q|
    |usbdev.u_reg.u_configin0_size0.q|
    |usbdev.u_reg.u_configin10_buffer10.q|
    |usbdev.u_reg.u_configin10_size10.q|
    |usbdev.u_reg.u_configin11_buffer11.q|
    |usbdev.u_reg.u_configin11_size11.q|
    |usbdev.u_reg.u_configin1_buffer1.q|
    |usbdev.u_reg.u_configin1_size1.q|
    |usbdev.u_reg.u_configin2_buffer2.q|
    |usbdev.u_reg.u_configin2_size2.q|
    |usbdev.u_reg.u_configin3_buffer3.q|
    |usbdev.u_reg.u_configin3_size3.q|
    |usbdev.u_reg.u_configin4_buffer4.q|
    |usbdev.u_reg.u_configin4_size4.q|
    |usbdev.u_reg.u_configin5_buffer5.q|
    |usbdev.u_reg.u_configin5_size5.q|
    |usbdev.u_reg.u_configin6_buffer6.q|
    |usbdev.u_reg.u_configin6_size6.q|
    |usbdev.u_reg.u_configin7_buffer7.q|
    |usbdev.u_reg.u_configin7_size7.q|
    |usbdev.u_reg.u_configin8_buffer8.q|
    |usbdev.u_reg.u_configin8_size8.q|
    |usbdev.u_reg.u_configin9_buffer9.q|
    |usbdev.u_reg.u_configin9_size9.q|
    |usbdev.u_reg.u_data_toggle_clear_clear0.q|
    |usbdev.u_reg.u_data_toggle_clear_clear0.qe|
    |usbdev.u_reg.u_data_toggle_clear_clear1.q|
    |usbdev.u_reg.u_data_toggle_clear_clear10.q|
    |usbdev.u_reg.u_data_toggle_clear_clear11.q|
    |usbdev.u_reg.u_data_toggle_clear_clear2.q|
    |usbdev.u_reg.u_data_toggle_clear_clear3.q|
    |usbdev.u_reg.u_data_toggle_clear_clear4.q|
    |usbdev.u_reg.u_data_toggle_clear_clear5.q|
    |usbdev.u_reg.u_data_toggle_clear_clear6.q|
    |usbdev.u_reg.u_data_toggle_clear_clear7.q|
    |usbdev.u_reg.u_data_toggle_clear_clear8.q|
    |usbdev.u_reg.u_data_toggle_clear_clear9.q|
    |usbdev.u_reg.u_intr_enable_av_empty.q|
    |usbdev.u_reg.u_intr_enable_av_overflow.q|
    |usbdev.u_reg.u_intr_enable_connected.q|
    |usbdev.u_reg.u_intr_enable_disconnected.q|
    |usbdev.u_reg.u_intr_enable_frame.q|
    |usbdev.u_reg.u_intr_enable_host_lost.q|
    |usbdev.u_reg.u_intr_enable_link_in_err.q|
    |usbdev.u_reg.u_intr_enable_link_reset.q|
    |usbdev.u_reg.u_intr_enable_link_resume.q|
    |usbdev.u_reg.u_intr_enable_link_suspend.q|
    |usbdev.u_reg.u_intr_enable_pkt_received.q|
    |usbdev.u_reg.u_intr_enable_pkt_sent.q|
    |usbdev.u_reg.u_intr_enable_rx_bitstuff_err.q|
    |usbdev.u_reg.u_intr_enable_rx_crc_err.q|
    |usbdev.u_reg.u_intr_enable_rx_full.q|
    |usbdev.u_reg.u_intr_enable_rx_pid_err.q|
    |usbdev.u_reg.u_intr_state_av_empty.q|
    |usbdev.u_reg.u_intr_state_av_overflow.q|
    |usbdev.u_reg.u_intr_state_connected.q|
    |usbdev.u_reg.u_intr_state_disconnected.q|
    |usbdev.u_reg.u_intr_state_frame.q|
    |usbdev.u_reg.u_intr_state_host_lost.q|
    |usbdev.u_reg.u_intr_state_link_in_err.q|
    |usbdev.u_reg.u_intr_state_link_reset.q|
    |usbdev.u_reg.u_intr_state_link_resume.q|
    |usbdev.u_reg.u_intr_state_link_suspend.q|
    |usbdev.u_reg.u_intr_state_pkt_received.q|
    |usbdev.u_reg.u_intr_state_pkt_sent.q|
    |usbdev.u_reg.u_intr_state_rx_bitstuff_err.q|
    |usbdev.u_reg.u_intr_state_rx_crc_err.q|
    |usbdev.u_reg.u_intr_state_rx_full.q|
    |usbdev.u_reg.u_intr_state_rx_pid_err.q|
    |usbdev.u_reg.u_iso_iso0.q|
    |usbdev.u_reg.u_iso_iso1.q|
    |usbdev.u_reg.u_iso_iso10.q|
    |usbdev.u_reg.u_iso_iso11.q|
    |usbdev.u_reg.u_iso_iso2.q|
    |usbdev.u_reg.u_iso_iso3.q|
    |usbdev.u_reg.u_iso_iso4.q|
    |usbdev.u_reg.u_iso_iso5.q|
    |usbdev.u_reg.u_iso_iso6.q|
    |usbdev.u_reg.u_iso_iso7.q|
    |usbdev.u_reg.u_iso_iso8.q|
    |usbdev.u_reg.u_iso_iso9.q|
    |usbdev.u_reg.u_phy_config_eop_single_bit.q|
    |usbdev.u_reg.u_phy_config_override_pwr_sense_en.q|
    |usbdev.u_reg.u_phy_config_override_pwr_sense_val.q|
    |usbdev.u_reg.u_phy_config_rx_differential_mode.q|
    |usbdev.u_reg.u_phy_config_tx_differential_mode.q|
    |usbdev.u_reg.u_reg_if.error|
    |usbdev.u_reg.u_reg_if.reqid|
    |usbdev.u_reg.u_reg_if.reqsz|
    |usbdev.u_reg.u_reg_if.rspop|
    |usbdev.u_reg.u_reg_if.outstanding|
    |usbdev.u_reg.u_rxenable_out_out0.q|
    |usbdev.u_reg.u_rxenable_out_out1.q|
    |usbdev.u_reg.u_rxenable_out_out10.q|
    |usbdev.u_reg.u_rxenable_out_out11.q|
    |usbdev.u_reg.u_rxenable_out_out2.q|
    |usbdev.u_reg.u_rxenable_out_out3.q|
    |usbdev.u_reg.u_rxenable_out_out4.q|
    |usbdev.u_reg.u_rxenable_out_out5.q|
    |usbdev.u_reg.u_rxenable_out_out6.q|
    |usbdev.u_reg.u_rxenable_out_out7.q|
    |usbdev.u_reg.u_rxenable_out_out8.q|
    |usbdev.u_reg.u_rxenable_out_out9.q|
    |usbdev.u_reg.u_rxenable_setup_setup0.q|
    |usbdev.u_reg.u_rxenable_setup_setup1.q|
    |usbdev.u_reg.u_rxenable_setup_setup10.q|
    |usbdev.u_reg.u_rxenable_setup_setup11.q|
    |usbdev.u_reg.u_rxenable_setup_setup2.q|
    |usbdev.u_reg.u_rxenable_setup_setup3.q|
    |usbdev.u_reg.u_rxenable_setup_setup4.q|
    |usbdev.u_reg.u_rxenable_setup_setup5.q|
    |usbdev.u_reg.u_rxenable_setup_setup6.q|
    |usbdev.u_reg.u_rxenable_setup_setup7.q|
    |usbdev.u_reg.u_rxenable_setup_setup8.q|
    |usbdev.u_reg.u_rxenable_setup_setup9.q|
    |usbdev.u_reg.u_socket.num_req_outstanding|
    |usbdev.u_reg.u_socket.dev_select_outstanding|
    |usbdev.u_reg.u_socket.err_resp.err_rsp_pending|
    |usbdev.u_reg.u_socket.err_resp.err_opcode|
    |usbdev.u_reg.u_socket.err_resp.err_source|
    |usbdev.u_reg.u_socket.err_resp.err_size|
    |usbdev.u_reg.u_socket.err_resp.err_req_pending|
    |usbdev.u_reg.u_usbctrl_device_address.q|
    |usbdev.u_reg.u_usbctrl_enable.q|
    |usbdev.u_tlul2sram.u_reqfifo.gen_normal_fifo.fifo_rptr|
    |usbdev.u_tlul2sram.u_reqfifo.gen_normal_fifo.fifo_wptr|
    |usbdev.u_tlul2sram.u_rspfifo.gen_normal_fifo.fifo_rptr|
    |usbdev.u_tlul2sram.u_rspfifo.gen_normal_fifo.fifo_wptr|
    |usbdev.usbdev_avfifo.storage_first|
    |usbdev.usbdev_avfifo.fifo_rptr_sync|
    |usbdev.usbdev_avfifo.fifo_wptr_gray|
    |usbdev.usbdev_avfifo.fifo_wptr|
    |usbdev.usbdev_avfifo.sync_rptr.q|
    |usbdev.usbdev_data_toggle_clear.src_level|
    |usbdev.usbdev_devclr.dst_level_q|
    |usbdev.usbdev_devclr.prim_flop_2sync.q|
    |usbdev.usbdev_outrdyclr.dst_level_q|
    |usbdev.usbdev_outrdyclr.prim_flop_2sync.q|
    |usbdev.usbdev_resume.dst_level_q|
    |usbdev.usbdev_resume.prim_flop_2sync.q|
    |usbdev.usbdev_rxfifo.fifo_rptr_gray|
    |usbdev.usbdev_rxfifo.fifo_rptr|
    |usbdev.usbdev_rxfifo.sync_wptr.q|
    |usbdev.usbdev_setsent.dst_level_q|
    |usbdev.usbdev_setsent.prim_flop_2sync.q|
    |usbdev.usbdev_sync_in_err.dst_level_q|
    |usbdev.usbdev_sync_in_err.prim_flop_2sync.q|
    |spi_device.u_fwmode_arb.u_req_fifo.gen_normal_fifo.storage|
    |spi_device.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.mem|
    |spi_device.u_tx_fifo.storage_rest|
    |tl_adapter_ram_main.u_rspfifo.gen_normal_fifo.storage|
    |tl_adapter_rom.u_rspfifo.gen_normal_fifo.storage|
    |u_rom_rom.gen_mem_generic.u_impl_generic.mem|
    |u_xbar_main.u_asf_21.rspfifo.storage_rest|
    |uart.uart_core.u_uart_rxfifo.gen_normal_fifo.storage|
    |uart.uart_core.u_uart_txfifo.gen_normal_fifo.storage|
    |usbdev.usbdev_avfifo.storage_rest|
    |u_ram1p_ram_main.gen_mem_generic.u_impl_generic.rdata_o|
    |u_rom_rom.gen_mem_generic.u_impl_generic.dout_o|
    |usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.a_rdata_o|
    |core.tl_i_source|
    |core.tl_d_source|
    |spi_device.u_rx_fifo.sync_wptr.intq|
    |spi_device.u_rxf_ctrl.sram_wdata|
    |spi_device.u_rxf_overflow.prim_flop_2sync.intq|
    |spi_device.u_sync_csb.intq|
    |spi_device.u_sync_rxf.intq|
    |spi_device.u_sync_txe.intq|
    |spi_device.u_tx_fifo.sync_rptr.intq|
    |spi_device.u_txf_underflow.prim_flop_2sync.intq|
    |tl_adapter_ram_main.u_reqfifo.gen_normal_fifo.fifo_wptr|
    |tl_adapter_rom.u_reqfifo.gen_normal_fifo.fifo_wptr|
    |u_ram1p_ram_main.gen_mem_generic.u_impl_generic.rvalid_o|
    |u_rom_rom.gen_mem_generic.u_impl_generic.dvalid_o|
    |u_xbar_main.u_asf_21.reqfifo.storage_first|
    |u_xbar_main.u_asf_21.reqfifo.fifo_wptr_gray|
    |u_xbar_main.u_asf_21.reqfifo.fifo_wptr|
    |u_xbar_main.u_s1n_15.num_req_outstanding|
    |u_xbar_main.u_s1n_15.dev_select_outstanding|
    |u_xbar_main.u_s1n_15.err_resp.err_opcode|
    |u_xbar_main.u_s1n_15.err_resp.err_source|
    |u_xbar_main.u_s1n_15.err_resp.err_size|
    |u_xbar_main.u_s1n_15.err_resp.err_req_pending|
    |u_xbar_main.u_s1n_20.num_req_outstanding|
    |u_xbar_main.u_s1n_20.dev_select_outstanding|
    |u_xbar_main.u_s1n_20.err_resp.err_opcode|
    |u_xbar_main.u_s1n_20.err_resp.err_source|
    |u_xbar_main.u_s1n_20.err_resp.err_size|
    |u_xbar_main.u_s1n_20.err_resp.err_req_pending|
    |u_xbar_main.u_sm1_16.gen_arb_ppc.u_reqarb.gen_normal_case.mask|
    |u_xbar_main.u_sm1_18.gen_arb_ppc.u_reqarb.gen_normal_case.mask|
    |uart.uart_core.sync_rx.intq|
    |usbdev.cdc_usb_to_sys.intq|
    |usbdev.i_usbdev_iomux.cdc_io_to_sys.intq|
    |usbdev.sync_usb_event_av_empty.prim_flop_2sync.intq|
    |usbdev.sync_usb_event_frame.prim_flop_2sync.intq|
    |usbdev.sync_usb_event_rx_bitstuff_err.prim_flop_2sync.intq|
    |usbdev.sync_usb_event_rx_crc_err.prim_flop_2sync.intq|
    |usbdev.sync_usb_event_rx_full.prim_flop_2sync.intq|
    |usbdev.sync_usb_event_rx_pid_err.prim_flop_2sync.intq|
    |usbdev.syncevent.prim_flop_2sync.intq|
    |usbdev.u_reg.u_configin0_pend0.q|
    |usbdev.u_reg.u_configin0_rdy0.q|
    |usbdev.u_reg.u_configin10_pend10.q|
    |usbdev.u_reg.u_configin10_rdy10.q|
    |usbdev.u_reg.u_configin11_pend11.q|
    |usbdev.u_reg.u_configin11_rdy11.q|
    |usbdev.u_reg.u_configin1_pend1.q|
    |usbdev.u_reg.u_configin1_rdy1.q|
    |usbdev.u_reg.u_configin2_pend2.q|
    |usbdev.u_reg.u_configin2_rdy2.q|
    |usbdev.u_reg.u_configin3_pend3.q|
    |usbdev.u_reg.u_configin3_rdy3.q|
    |usbdev.u_reg.u_configin4_pend4.q|
    |usbdev.u_reg.u_configin4_rdy4.q|
    |usbdev.u_reg.u_configin5_pend5.q|
    |usbdev.u_reg.u_configin5_rdy5.q|
    |usbdev.u_reg.u_configin6_pend6.q|
    |usbdev.u_reg.u_configin6_rdy6.q|
    |usbdev.u_reg.u_configin7_pend7.q|
    |usbdev.u_reg.u_configin7_rdy7.q|
    |usbdev.u_reg.u_configin8_pend8.q|
    |usbdev.u_reg.u_configin8_rdy8.q|
    |usbdev.u_reg.u_configin9_pend9.q|
    |usbdev.u_reg.u_configin9_rdy9.q|
    |usbdev.u_reg.u_in_sent_sent0.q|
    |usbdev.u_reg.u_in_sent_sent1.q|
    |usbdev.u_reg.u_in_sent_sent10.q|
    |usbdev.u_reg.u_in_sent_sent11.q|
    |usbdev.u_reg.u_in_sent_sent2.q|
    |usbdev.u_reg.u_in_sent_sent3.q|
    |usbdev.u_reg.u_in_sent_sent4.q|
    |usbdev.u_reg.u_in_sent_sent5.q|
    |usbdev.u_reg.u_in_sent_sent6.q|
    |usbdev.u_reg.u_in_sent_sent7.q|
    |usbdev.u_reg.u_in_sent_sent8.q|
    |usbdev.u_reg.u_in_sent_sent9.q|
    |usbdev.u_reg.u_reg_if.rdata|
    |usbdev.u_reg.u_stall_stall0.q|
    |usbdev.u_reg.u_stall_stall1.q|
    |usbdev.u_reg.u_stall_stall10.q|
    |usbdev.u_reg.u_stall_stall11.q|
    |usbdev.u_reg.u_stall_stall2.q|
    |usbdev.u_reg.u_stall_stall3.q|
    |usbdev.u_reg.u_stall_stall4.q|
    |usbdev.u_reg.u_stall_stall5.q|
    |usbdev.u_reg.u_stall_stall6.q|
    |usbdev.u_reg.u_stall_stall7.q|
    |usbdev.u_reg.u_stall_stall8.q|
    |usbdev.u_reg.u_stall_stall9.q|
    |usbdev.usbdev_avfifo.sync_rptr.intq|
    |usbdev.usbdev_devclr.prim_flop_2sync.intq|
    |usbdev.usbdev_outrdyclr.prim_flop_2sync.intq|
    |usbdev.usbdev_resume.prim_flop_2sync.intq|
    |usbdev.usbdev_rxfifo.sync_wptr.intq|
    |usbdev.usbdev_setsent.prim_flop_2sync.intq|
    |usbdev.usbdev_sync_in_err.prim_flop_2sync.intq|
    |tl_adapter_ram_main.u_reqfifo.gen_normal_fifo.storage|
    |tl_adapter_rom.u_reqfifo.gen_normal_fifo.storage|
    |u_ram1p_ram_main.gen_mem_generic.u_impl_generic.mem|
    |u_xbar_main.u_asf_21.reqfifo.storage_rest|
    |usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.mem|
    ))
(provide spi-out-registers)
(define spi-out-registers
  '(
    |spi_device.txf_empty_q|
    |spi_device.u_txf_underflow.src_level|
    |spi_device.u_fwmode.miso_shift|
    |spi_device.u_fwmode.tx_state|
    |spi_device.u_fwmode.tx_bitcount|
    |spi_device.u_tx_fifo.fifo_rptr_gray|
    |spi_device.u_tx_fifo.fifo_rptr|
    |spi_device.u_tx_fifo.sync_wptr.q|
    |spi_device.u_tx_fifo.sync_wptr.intq|
  ))
(provide spi-in-registers)
(define spi-in-registers
  '(
    |spi_device.rxf_full_q|
    |spi_device.u_fwmode.rx_bitcount|
    |spi_device.u_rxf_overflow.src_level|
    |spi_device.u_fwmode.rx_data_q|
    |spi_device.u_rx_fifo.fifo_rptr_sync|
    |spi_device.u_rx_fifo.fifo_wptr_gray|
    |spi_device.u_rx_fifo.fifo_wptr|
    |spi_device.u_rx_fifo.sync_rptr.q|
    |spi_device.u_rx_fifo.sync_rptr.intq|
    |spi_device.u_rx_fifo.storage_first|
    |spi_device.u_rx_fifo.storage_rest|
    |spi_device.u_fwmode.current_cfg_rx_order|
  ))
(provide usb-registers)
(define usb-registers
  '(
    |usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.b_rdata_o|
    |usbdev.cdc_sys_to_usb.q|
    |usbdev.i_usbdev_iomux.cdc_io_to_usb.q|
    |usbdev.sync_usb_event_av_empty.src_level|
    |usbdev.sync_usb_event_rx_full.src_level|
    |usbdev.usbdev_avfifo.fifo_rptr_gray|
    |usbdev.usbdev_avfifo.fifo_rptr|
    |usbdev.usbdev_avfifo.sync_wptr.q|
    |usbdev.usbdev_data_toggle_clear.dst_level_q|
    |usbdev.usbdev_data_toggle_clear.prim_flop_2sync.q|
    |usbdev.usbdev_devclr.src_level|
    |usbdev.usbdev_impl.ns_cnt|
    |usbdev.usbdev_impl.pkt_start_rd|
    |usbdev.usbdev_impl.av_rready_o|
    |usbdev.usbdev_impl.wdata|
    |usbdev.usbdev_impl.std_write_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_ep_data_get_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_ep_get_addr_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.tx_data_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_put_addr_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.nak_out_transfer|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_data_put_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_data_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.addr_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.endp_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.frame_num_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.line_history_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.bit_phase_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.bitstuff_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.bitstuff_q2|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.bitstuff_q3|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.bitstuff_q4|
    |usbdev.usbdev_impl.u_usbdev_linkstate.link_inac_timer_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.link_inac_state_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.link_rst_timer_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.link_rst_state_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.link_state_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.filter_pwr_sense.stored_vector_q [4:0]|
    |usbdev.usbdev_impl.u_usbdev_linkstate.filter_pwr_sense.stored_value_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.filter_se0.stored_vector_q [4:0]|
    |usbdev.usbdev_impl.u_usbdev_linkstate.filter_se0.stored_value_q|
    |usbdev.usbdev_outrdyclr.src_level|
    |usbdev.usbdev_rdysync.q|
    |usbdev.usbdev_resume.src_level|
    |usbdev.usbdev_rxfifo.fifo_rptr_sync|
    |usbdev.usbdev_rxfifo.fifo_wptr_gray|
    |usbdev.usbdev_rxfifo.fifo_wptr|
    |usbdev.usbdev_rxfifo.sync_rptr.q|
    |usbdev.usbdev_sync_ep_cfg.q|
    |usbdev.usbdev_sync_in_err.src_level|
    |usbdev.event_link_reset_q|
    |usbdev.cdc_sys_to_usb.intq|
    |usbdev.i_usbdev_iomux.cdc_io_to_usb.intq|
    |usbdev.sync_usb_event_frame.src_level|
    |usbdev.sync_usb_event_rx_bitstuff_err.src_level|
    |usbdev.sync_usb_event_rx_crc_err.src_level|
    |usbdev.sync_usb_event_rx_pid_err.src_level|
    |usbdev.usbdev_avfifo.sync_wptr.intq|
    |usbdev.usbdev_data_toggle_clear.prim_flop_2sync.intq|
    |usbdev.usbdev_impl.frame_o|
    |usbdev.usbdev_impl.out_max_used_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.data_toggle_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_ep_current_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_ep_newpkt_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_ep_rollback_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_xfr_state|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_current_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_newpkt_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.current_xfer_setup_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.data_toggle_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_xfr_state|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_setup_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.full_pid_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.crc5_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.crc16_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.token_payload_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.rx_data_buffer_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.bitstuff_error_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.bitstuff_history_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.packet_valid_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_rx.line_state_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.out_state_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.oe_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.usb_d_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.usb_se0_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.dp_eop_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.crc16_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.state_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.data_shift_reg_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.oe_shift_reg_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.se0_shift_reg_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.data_payload_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.tx_data_get_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.byte_strobe_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.bit_history_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.bit_count_q|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_tx.pid_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.host_presence_timer|
    |usbdev.usbdev_impl.u_usbdev_linkstate.filter_idle.stored_vector_q [4:0]|
    |usbdev.usbdev_impl.u_usbdev_linkstate.filter_idle.stored_value_q|
    |usbdev.usbdev_rdysync.intq|
    |usbdev.usbdev_rxfifo.sync_rptr.intq|
    |usbdev.usbdev_setsent.src_level|
    |usbdev.usbdev_sync_ep_cfg.intq|
    ; handled separately with special hint
    ;|usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.mem|
    |usbdev.usbdev_rxfifo.storage_first|
    |usbdev.usbdev_rxfifo.storage_rest|
    |usbdev.u_memory_2p.b_rvalid_sram|
    |usbdev.usb_mem_b_req_q|
    |usbdev.usb_mem_b_rvalid_q|
    |usb_reset_sync.q|
    |usb_reset_sync.intq|
  ))

(provide main-to-spi-in-registers)
(define main-to-spi-in-registers
  '(
    spi_device.u_reg.u_cfg_rx_order.q
    spi_device.u_reg.u_control_rst_rxfifo.q
    spi_device.u_rx_fifo.fifo_rptr_gray
    ))

(provide main-to-spi-out-registers)
(define main-to-spi-out-registers
  '(
    spi_device.u_tx_fifo.storage_first
    spi_device.u_tx_fifo.storage_rest
    spi_device.u_reg.u_cfg_tx_order.q
    spi_device.u_reg.u_cfg_cpha.q
    spi_device.u_reg.u_control_rst_txfifo.q
    spi_device.u_tx_fifo.fifo_wptr_gray
    ))

(provide main-to-usb-registers)
(define main-to-usb-registers
  '(
    |usbdev.u_reg.u_configin0_buffer0.q|
    |usbdev.u_reg.u_configin0_rdy0.q|
    |usbdev.u_reg.u_configin0_size0.q|
    |usbdev.u_reg.u_configin1_buffer1.q|
    |usbdev.u_reg.u_configin1_rdy1.q|
    |usbdev.u_reg.u_configin1_size1.q|
    |usbdev.u_reg.u_configin2_buffer2.q|
    |usbdev.u_reg.u_configin2_rdy2.q|
    |usbdev.u_reg.u_configin2_size2.q|
    |usbdev.u_reg.u_configin3_buffer3.q|
    |usbdev.u_reg.u_configin3_rdy3.q|
    |usbdev.u_reg.u_configin3_size3.q|
    |usbdev.u_reg.u_configin4_buffer4.q|
    |usbdev.u_reg.u_configin4_rdy4.q|
    |usbdev.u_reg.u_configin4_size4.q|
    |usbdev.u_reg.u_configin5_buffer5.q|
    |usbdev.u_reg.u_configin5_rdy5.q|
    |usbdev.u_reg.u_configin5_size5.q|
    |usbdev.u_reg.u_configin6_buffer6.q|
    |usbdev.u_reg.u_configin6_rdy6.q|
    |usbdev.u_reg.u_configin6_size6.q|
    |usbdev.u_reg.u_configin7_buffer7.q|
    |usbdev.u_reg.u_configin7_rdy7.q|
    |usbdev.u_reg.u_configin7_size7.q|
    |usbdev.u_reg.u_configin8_buffer8.q|
    |usbdev.u_reg.u_configin8_rdy8.q|
    |usbdev.u_reg.u_configin8_size8.q|
    |usbdev.u_reg.u_configin9_buffer9.q|
    |usbdev.u_reg.u_configin9_rdy9.q|
    |usbdev.u_reg.u_configin9_size9.q|
    |usbdev.u_reg.u_configin10_buffer10.q|
    |usbdev.u_reg.u_configin10_rdy10.q|
    |usbdev.u_reg.u_configin10_size10.q|
    |usbdev.u_reg.u_configin11_buffer11.q|
    |usbdev.u_reg.u_configin11_rdy11.q|
    |usbdev.u_reg.u_configin11_size11.q|
    |usbdev.u_reg.u_data_toggle_clear_clear0.q|
    |usbdev.u_reg.u_data_toggle_clear_clear1.q|
    |usbdev.u_reg.u_data_toggle_clear_clear2.q|
    |usbdev.u_reg.u_data_toggle_clear_clear3.q|
    |usbdev.u_reg.u_data_toggle_clear_clear4.q|
    |usbdev.u_reg.u_data_toggle_clear_clear5.q|
    |usbdev.u_reg.u_data_toggle_clear_clear6.q|
    |usbdev.u_reg.u_data_toggle_clear_clear7.q|
    |usbdev.u_reg.u_data_toggle_clear_clear8.q|
    |usbdev.u_reg.u_data_toggle_clear_clear9.q|
    |usbdev.u_reg.u_data_toggle_clear_clear10.q|
    |usbdev.u_reg.u_data_toggle_clear_clear11.q|
    |usbdev.syncevent.d_sync_q|
    |usbdev.syncevent.prim_flop_2sync.q|
    |usbdev.u_reg.u_iso_iso0.q|
    |usbdev.u_reg.u_iso_iso1.q|
    |usbdev.u_reg.u_iso_iso2.q|
    |usbdev.u_reg.u_iso_iso3.q|
    |usbdev.u_reg.u_iso_iso4.q|
    |usbdev.u_reg.u_iso_iso5.q|
    |usbdev.u_reg.u_iso_iso6.q|
    |usbdev.u_reg.u_iso_iso7.q|
    |usbdev.u_reg.u_iso_iso8.q|
    |usbdev.u_reg.u_iso_iso9.q|
    |usbdev.u_reg.u_iso_iso10.q|
    |usbdev.u_reg.u_iso_iso11.q|
    |usbdev.usbdev_rxfifo.fifo_rptr_gray|
    |u_xbar_main.u_asf_21.reqfifo.fifo_rptr|
    |usbdev.u_reg.u_phy_config_eop_single_bit.q|
    |u_xbar_main.u_asf_21.reqfifo.sync_wptr.q|
    |usbdev.u_reg.u_phy_config_override_pwr_sense_en.q|
    |usbdev.u_reg.u_phy_config_override_pwr_sense_val.q|
    |usbdev.u_reg.u_phy_config_rx_differential_mode.q|
    |usbdev.u_reg.u_rxenable_out_out0.q|
    |usbdev.u_reg.u_rxenable_out_out1.q|
    |usbdev.u_reg.u_rxenable_out_out2.q|
    |usbdev.u_reg.u_rxenable_out_out3.q|
    |usbdev.u_reg.u_rxenable_out_out4.q|
    |usbdev.u_reg.u_rxenable_out_out5.q|
    |usbdev.u_reg.u_rxenable_out_out6.q|
    |usbdev.u_reg.u_rxenable_out_out7.q|
    |usbdev.u_reg.u_rxenable_out_out8.q|
    |usbdev.u_reg.u_rxenable_out_out9.q|
    |usbdev.u_reg.u_rxenable_out_out10.q|
    |usbdev.u_reg.u_rxenable_out_out11.q|
    |u_xbar_peri.u_s1n_6.num_req_outstanding|
    |u_xbar_peri.u_s1n_6.dev_select_outstanding|
    |u_xbar_main.u_asf_21.reqfifo.storage_first|
    |u_xbar_main.u_asf_21.reqfifo.storage_rest|
    |usbdev.usbdev_avfifo.storage_first|
    |usbdev.usbdev_avfifo.storage_rest|
    |usbdev.u_reg.u_rxenable_setup_setup0.q|
    |usbdev.u_reg.u_rxenable_setup_setup1.q|
    |usbdev.u_reg.u_rxenable_setup_setup2.q|
    |usbdev.u_reg.u_rxenable_setup_setup3.q|
    |usbdev.u_reg.u_rxenable_setup_setup4.q|
    |usbdev.u_reg.u_rxenable_setup_setup5.q|
    |usbdev.u_reg.u_rxenable_setup_setup6.q|
    |usbdev.u_reg.u_rxenable_setup_setup7.q|
    |usbdev.u_reg.u_rxenable_setup_setup8.q|
    |usbdev.u_reg.u_rxenable_setup_setup9.q|
    |usbdev.u_reg.u_rxenable_setup_setup10.q|
    |usbdev.u_reg.u_rxenable_setup_setup11.q|
    |usbdev.u_reg.u_socket.num_req_outstanding|
    |usbdev.u_reg.u_socket.dev_select_outstanding|
    |usbdev.u_reg.u_stall_stall0.q|
    |usbdev.u_reg.u_stall_stall1.q|
    |usbdev.u_reg.u_stall_stall2.q|
    |usbdev.u_reg.u_stall_stall3.q|
    |usbdev.u_reg.u_stall_stall4.q|
    |usbdev.u_reg.u_stall_stall5.q|
    |usbdev.u_reg.u_stall_stall6.q|
    |usbdev.u_reg.u_stall_stall7.q|
    |usbdev.u_reg.u_stall_stall8.q|
    |usbdev.u_reg.u_stall_stall9.q|
    |usbdev.u_reg.u_stall_stall10.q|
    |usbdev.u_reg.u_stall_stall11.q|
    |usbdev.u_reg.u_usbctrl_device_address.q|
    |usbdev.u_reg.u_usbctrl_enable.q|
    |usbdev.u_tlul2sram.u_reqfifo.gen_normal_fifo.fifo_rptr|
    |usbdev.u_tlul2sram.u_reqfifo.gen_normal_fifo.fifo_wptr|
    |usbdev.usbdev_avfifo.fifo_wptr_gray|
    |usbdev.usbdev_data_toggle_clear.src_level|

    ; not a CDC register, but combinationally affects output that's otherwise
    ; generated from USB clock domain. Add it to the proof boundary so we can
    ; prove that output safe in USB peripheral proof.
    usbdev.u_reg.u_phy_config_tx_differential_mode.q
    ))

(provide spi-in-to-main-registers)
(define spi-in-to-main-registers
  '(
    spi_device.u_rx_fifo.fifo_wptr_gray
    spi_device.u_rxf_overflow.src_level
    spi_device.rxf_full_q
    spi_device.u_rx_fifo.storage_first
    spi_device.u_rx_fifo.storage_rest
    ))

(provide spi-out-to-main-registers)
(define spi-out-to-main-registers
  '(
    spi_device.u_tx_fifo.fifo_rptr_gray
    spi_device.u_txf_underflow.src_level
    spi_device.txf_empty_q
    ))

(provide usb-to-main-registers)
(define usb-to-main-registers
  '(
    usbdev.usbdev_resume.src_level
    usbdev.usbdev_sync_in_err.src_level
    usbdev.usbdev_rxfifo.fifo_wptr_gray
    usbdev.usbdev_avfifo.fifo_rptr_gray
    usbdev.usbdev_devclr.src_level
    usbdev.sync_usb_event_rx_full.src_level
    usbdev.usbdev_impl.u_usbdev_linkstate.link_rst_state_q
    usbdev.usbdev_outrdyclr.src_level
    usbdev.usbdev_impl.u_usbdev_linkstate.link_state_q
    usbdev.sync_usb_event_av_empty.src_level
    ; TODO: why were these not autodetected?
    usbdev.sync_usb_event_rx_pid_err.src_level
    usbdev.usbdev_setsent.src_level
    usbdev.sync_usb_event_rx_crc_err.src_level
    usbdev.sync_usb_event_rx_bitstuff_err.src_level
    usbdev.sync_usb_event_frame.src_level
    |usbdev.usbdev_impl.frame_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_in_pe.in_ep_current_o|
    |usbdev.usbdev_impl.u_usb_fs_nb_pe.u_usb_fs_nb_out_pe.out_ep_current_o|
    |usbdev.event_link_reset_q|
    |usbdev.usbdev_impl.u_usbdev_linkstate.host_presence_timer|
    usbdev.usbdev_rxfifo.storage_first
    usbdev.usbdev_rxfifo.storage_rest
    ))

(provide non-reset-registers)
(define non-reset-registers
  '(
    ; regs proper
    |core.u_core.if_stage_i.prefetch_buffer_i.fetch_addr_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.stored_addr_q|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.rdata_q [95:64]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.err_q [2]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.rdata_q [63:32]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.err_q [1]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.rdata_q [31:0]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.err_q [0]|
    |core.u_core.if_stage_i.prefetch_buffer_i.fifo_i.instr_addr_q|
    |spi_device.u_fwmode.miso_shift|
    |spi_device.u_fwmode.rx_data_q|
    |spi_device.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.b_rdata_o|
    |spi_device.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.a_rdata_o|
    |spi_device.u_tlul2sram.u_reqfifo.gen_normal_fifo.storage[0]|
    |spi_device.u_tlul2sram.u_rspfifo.gen_normal_fifo.storage[0]|
    |u_ram1p_ram_main.gen_mem_generic.u_impl_generic.rdata_o|
    |u_rom_rom.gen_mem_generic.u_impl_generic.dout_o|
    |usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.b_rdata_o|
    |usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.a_rdata_o|
    |usbdev.u_tlul2sram.u_reqfifo.gen_normal_fifo.storage[0]|
    |usbdev.u_tlul2sram.u_rspfifo.gen_normal_fifo.storage[0]|

    ; memories
    spi_device.u_tx_fifo.storage_rest
    usbdev.usbdev_avfifo.storage_rest
    u_xbar_main.u_asf_21.reqfifo.storage_rest
    usbdev.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.mem
    uart.uart_core.u_uart_txfifo.gen_normal_fifo.storage
    uart.uart_core.u_uart_rxfifo.gen_normal_fifo.storage
    tl_adapter_rom.u_reqfifo.gen_normal_fifo.storage
    tl_adapter_rom.u_rspfifo.gen_normal_fifo.storage
    tl_adapter_ram_main.u_reqfifo.gen_normal_fifo.storage
    tl_adapter_ram_main.u_rspfifo.gen_normal_fifo.storage
    u_xbar_main.u_asf_21.rspfifo.storage_rest
    u_ram1p_ram_main.gen_mem_generic.u_impl_generic.mem
    spi_device.u_fwmode_arb.u_req_fifo.gen_normal_fifo.storage
    spi_device.u_memory_2p.gen_srammem.u_mem.gen_mem_generic.u_impl_generic.mem
    ))
